bootkali improved

diff --git a/assets/scripts/bootkali b/assets/scripts/bootkali
--- a/assets/scripts/bootkali
+++ b/assets/scripts/bootkali
@@ -150,20 +150,31 @@ else
 
 	fi
 	if [ "$1" == "duck-hunt-run" ]; then
+	    # Check if hid-keyboard binary is present at $mnt/usr/bin/
+	    if [ ! -x $mnt/usr/bin/hid-keyboard ]; then
+	        if [ -e /sdcard/nh_files/modules/hid-keyboard ]; then
+	            cp /sdcard/nh_files/modules/hid-keyboard $mnt/usr/bin/
+	            $busybox chroot $mnt /bin/chmod 755 /usr/bin/hid-keyboard
+	        else
+	            echo " [-] hid-keyboard not found in /usr/bin"
+	            exit 1
+	        fi
+	    fi
+
 		if [ ! -f /data/local/nhsystem/kali-armhf$2 ]; then
 			echo "File not found"
 		else
 			echo "File /data/local/nhsystem/kali-armhf$2 found"
 			COUNT=0
-            until echo volume-up | hid-keyboard /dev/hidg0 keyboard > /dev/null 2>&1; do
-                sleep 1
-                COUNT=$((COUNT+1))
-                if [ $COUNT -gt 60 ]; then  #60 seconds
-                    exit
-                fi
-            done
-            echo "USB cable plugged"
-			sh /sdcard/nh_files/modules/duckout.sh
+            until $busybox chroot $mnt /bin/bash -c "echo volume-up | hid-keyboard /dev/hidg0 keyboard > /dev/null 2>&1"; do
+				sleep 1
+				COUNT=$((COUNT+1))
+				if [ $COUNT -gt 60 ]; then  #60 seconds
+					exit 1
+				fi
+			done
+			echo "USB cable plugged"
+			$busybox chroot $mnt /bin/bash $2
 		fi
 	fi
 
