Update killkali

diff --git a/assets/scripts/killkali b/assets/scripts/killkali
--- a/assets/scripts/killkali
+++ b/assets/scripts/killkali
@@ -1,128 +1,396 @@
 #!/system/bin/sh
 
+######### IMPORT BOOTKALI ENVIRONMENT #########
 SCRIPT_PATH=$(readlink -f $0)
-. ${SCRIPT_PATH%/*}/bootkali_log
+. ${SCRIPT_PATH%/*}/bootkali_env
 
-if [ -x /system/xbin/busybox_nh ]; then
-	busybox=/system/xbin/busybox_nh
-elif [ -x /system/xbin/busybox ]; then
-	busybox=/system/xbin/busybox
-elif [ -x /system/bin/busybox ]; then
-	busybox=/system/bin/busybox
-elif [ -x /data/adb/magisk/busybox ]; then
-	busybox=/data/adb/magisk/busybox
+# EXECUTE CHROOT / ADD ARGUMENTS TO LAUNCH SPECIFIC PROGRAMS
+#
+# ---------------  START / STOP ARGUMENTS  ----------------- #
+# apache, beef-xss, dhcp, dnsmasq, hid-cmd, openvpn, ssh,
+# mana {stop}, mana-full, mana-noup, mana-noupeap, mana-simple,
+# mana-bdf, msf, fruitywifi
+# ---------------  SINGLE ARGUMENT ------------------------- #
+# hid-cmd, hid-cmd-elevated-win[7-8], wifite, iptables, update
+# start-rev-met, start-rev-met-elevated-win[8-7]
+
+if [ $# -eq 0 ]; then
+	$busybox chroot $mnt /bin/bash -c "if [ ! -f $HOME/.hushlogin ]; then touch $HOME/.hushlogin; fi; /bin/login -f root"
 else
-	bklog "Busybox not found!  Install it, dummy!"
-	exit
-fi
+	#APACHE
 
-export bin=/system/bin
-export mnt=/data/local/nhsystem/kali-armhf
-PRESERVED_PATH=$PATH
-export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
-export TERM=linux
-export HOME=/root
-export LOGNAME=root
-unset LD_PRELOAD
+	if [ "$1" == "apache" ] && [ "$2" == "start" ]; then
+		$busybox chroot $mnt sudo service apache2 start
+	fi
+	if [ "$1" == "apache" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt sudo service apache2 stop
+	fi
 
-# set shmmax to 128mb to free memory#
+	#BEEF-XSS
 
-$busybox sysctl -w kernel.shmmax=134217728
+	if [ "$1" == "beef-xss" ] && [ "$2" == "start" ]; then
+		LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8 $busybox chroot $mnt sudo service beef-xss start
+		sleep 10
+		am start -a android.intent.action.VIEW -d http://127.0.0.1:3000/ui/authentication
+	fi
+	if [ "$1" == "beef-xss" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt sudo service beef-xss stop
+	fi
 
-bklog "[!] Shutting down dbus"
-$busybox chroot $mnt /etc/init.d/dbus stop
+	#DHCP
 
-bklog "[!] Shutting down SSH Server"
-$busybox chmod 666 /dev/null
+	if [ "$1" == "dhcp" ] && [ "$2" == "start" ]; then
+		$busybox chroot $mnt sudo service isc-dhcp-server start
+	fi
+	if [ "$1" == "dhcp" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt sudo service isc-dhcp-server stop
+	fi
 
-$busybox chroot $mnt /etc/init.d/ssh stop
+	#DNSMASQ
 
-bklog "[!] Shutting down Postgresql"
-$busybox chroot $mnt /etc/init.d/postgresql stop
+	if [ "$1" == "dnsmasq" ] && [ "$2" == "start" ]; then
+		$busybox chroot $mnt service dnsmasq start
+	fi
+	if [ "$1" == "dnsmasq" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt service dnsmasq stop
+	fi
 
-bklog "[!] Shutting down VNCserver"
-pkill Xtightvnc
-rm -f $mnt/root/.vnc/*.log *.pid > /dev/null 2>&1
-rm -f $mnt/tmp/.X*-.lock .X*-unix/* > /dev/null 2>&1
+	#HOSTAPD
 
-########## Kill all running kali terminals first ##########
-bklog "[!] Killing all running kali terminals.."
-kill_pids
+	if [ "$1" == "hostapd" ] && [ "$2" == "start" ]; then
+		#$busybox chroot $mnt /usr/sbin/hostapd /etc/hostapd/hostapd.conf >/dev/null 2>&1 </dev/null &
+		$busybox chroot $mnt service hostapd start
+	fi
+	if [ "$1" == "hostapd" ] && [ "$2" == "stop" ]; then
+		#killall hostapd 2> /dev/null
+		$busybox chroot $mnt service hostapd stop
+	fi
 
-# unmount everything
+	#IPTABLES
 
-bklog "[!] Removing all Kali mounts .."
-$busybox umount $mnt/dev/shm && echo "unmounted shm"
-$busybox umount $mnt/dev/pts && echo "unmounted pts"
-$busybox umount $mnt/dev && echo "unmounted dev"
-$busybox umount $mnt/proc && echo "unmounted proc"
-$busybox umount $mnt/sys && echo "unmounted sys"
-$busybox umount $mnt/system && echo "unmounted system"
-$busybox umount $mnt/lib/modules && echo "unmounted modules"
-$busybox umount $mnt/sdcard && echo "unmounted $mnt$sdcard"
-$busybox umount $mnt/external_sd && echo "unmounted external_sd"
+	if [ "$1" == "iptables" ]; then
+		$busybox chroot $mnt sh /sdcard/nh_files/configs/iptables.conf
+	fi
 
-if [ -d "$mnt/dev/shm" ]; then
-    rmdir $mnt/dev/shm
-fi
+	#MANA (is now using only the stop scripts)
 
-if [ -d "$mnt/dev/pts" ]; then
-    rmdir $mnt/dev/pts
-fi
+	if [ "$1" == "mana-lollipop" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt /usr/bin/stop-mana-lollipop
+	fi
+	if [ "$1" == "mana-kitkat" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt /usr/bin/stop-mana-kitkat
+	fi
 
-if [ -d "$mnt/dev" ]; then
-    rmdir $mnt/dev
-fi
+	#MSF
 
-if [ -d "$mnt/proc" ]; then
-    rmdir $mnt/proc
-fi
+	if [ "$1" == "msf" ] && [ "$2" == "start" ]; then
+		$busybox chroot $mnt start-msf.sh
+	fi
+	if [ "$1" == "msf" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt stop-msf.sh
+	fi
 
-if [ -d "$mnt/sys" ]; then
-    rmdir $mnt/sys
-fi
+	#OPENVPN
 
-###### umount the chroot as well if it is being mounted. Here the directory method will not be affected. ######
-if [ "$(losetup -a | grep $chroot_image)" ]; then
-    if [ "$($busybox umount $mnt 2>&1 > /dev/null)" ]; then
-        bklog "[-] Unable to umount the kali chroot image."
-        bklog "[!] If so, please try to close all the kali terminals first, secondly manually umount all the mointpoints on kali chroot, and lastly kill all the running services like ssh, vnc, webservice etc..."
-    else
-	bklog "[+] umounted kali-armhf"
+	if [ "$1" == "openvpn" ] && [ "$2" == "start" ]; then
+		$busybox chroot $mnt service openvpn start
+	fi
+	if [ "$1" == "openvpn" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt service openvpn stop
+	fi
+
+	#Open VNC
+
+	if [ "$1" == "vnc" ] && [ "$2" == "start" ]; then
+        	        	sh /data/data/com.offsec.nethunter/files/scripts/start-vnc $3 $4 $5 $6 $7 $8
+	fi
+
+	# HID Keyboard Command a.k.a Teensy style
+	# Supported keyboard layouts: US, FR, EN, ES
+	# We can pass language options to bootkali like:
+	# bootkali start-rev-met --us | --fr | --de | --es
+
+	if [ "$1" == "start-rev-met" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh start-rev-met "$2" | /system/bin/sh
+	fi
+	if [ "$1" == "start-rev-met-elevated-win7" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh start-rev-met-elevated-win7 $2 | /system/bin/sh
+	fi
+	if [ "$1" == "start-rev-met-elevated-win8" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh start-rev-met-elevated-win8 $2 | /system/bin/sh
+	fi
+	if [ "$1" == "start-rev-met-elevated-win10" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh start-rev-met-elevated-win10 $2 | /system/bin/sh
+	fi
+	if [ "$1" == "hid-cmd-elevated-win10" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh hid-cmd-elevated-win10 "$2" | /system/bin/sh
+	fi
+	if [ "$1" == "hid-cmd-elevated-win8" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh hid-cmd-elevated-win8 "$2" | /system/bin/sh
+	fi
+	if [ "$1" == "hid-cmd-elevated-win7" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh hid-cmd-elevated-win7 "$2" | /system/bin/sh
+	fi
+	if [ "$1" == "hid-cmd" ]; then
+		$busybox chroot $mnt sudo /usr/bin/hid-all.sh hid-cmd "$2" | /system/bin/sh
+	fi
+
+	# DUCK HUNT - Rubber Ducky conversion script to nethunter
+	# Requires argument to generate based on language. e.g.:
+	# bootkali duck-hunt-convert us /sdcard/nh_files/modules/ducktest.txt /opt/duckout.sh
+	# Languages supported: us, fr, de, es,sv, it, uk, ru, dk, no, pt, be
+	#
+	# Run converted script with:
+	# bootkali duck-hunt-run {/opt/duckout.sh}
+
+	if [ "$1" == "duck-hunt-convert" ]; then
+		$busybox chroot $mnt /usr/bin/python2.7 /sdcard/nh_files/modules/duckhunter.py -l $2 $3 $4
+		## $busybox chroot $mnt sudo chmod 755 $4
+
+	fi
+	if [ "$1" == "duck-hunt-run" ]; then
+		# Check if hid-keyboard binary is present at $mnt/usr/bin/
+		if [ ! -x $mnt/usr/bin/hid-keyboard ]; then
+		    bklog "[!] No hid-keyboard executable is found in kali, now trying to compile it."
+		    if [ -e /sdcard/nh_files/modules/hid-keyboard.c ]; then
+		        $busybox chroot $mnt /usr/bin/sudo apt install -y python gcc binutils
+		        $busybox chroot $mnt /usr/bin/sudo gcc /sdcard/nh_files/modules/hid-keyboard.c -o /usr/bin/hid-keyboard
+				$busybox chroot $mnt /usr/bin/sudo chmod 755 /usr/bin/hid-keyboard
+			fi
+		    if [ ! -x $mnt/usr/bin/hid-keyboard ]; then
+				bklog "[-] Failed to compile hid-keyboard executable to /usr/bin/ , script aborted."
+				exit 1
+		    fi
+		    bklog "[+] hid-keyboard executable is successfully compiled."
+		fi
+
+		if [ ! -f /data/local/nhsystem/kali-armhf$2 ]; then
+			bklog "[-] File not found"
+		else
+			bklog "[+] File /data/local/nhsystem/kali-armhf$2 found"
+			COUNT=0
+            		until $busybox chroot $mnt /bin/bash -c "echo volume-up | hid-keyboard /dev/hidg0 keyboard > /dev/null 2>&1"; do
+				sleep 1
+				COUNT=$((COUNT+1))
+				if [ $COUNT -gt 60 ]; then  #60 seconds
+					exit 1
+				fi
+		    done
+		    bklog "[+] USB cable plugged, executing attack..."
+		    $busybox chroot $mnt /bin/bash $2
+		fi
+	fi
+
+	# File2HID will convert any file or string to HID for keyboard goodness
+	# bootkali file2hid-file -f fileinput.txt -l us
+	# bootkali file2hid-string -s "string" -l us
+
+	if [ "$1" == "file2hid-file" ]; then
+		$busybox chroot $mnt sudo python /sdcard/nh_files/modules/filetohid.py -f $2 -l us
+	fi
+	if [ "$1" == "file2hid-string" ]; then
+		$busybox chroot $mnt sudo python /sdcard/nh_files/modules/filetohid.py -s $2 -l us
+	fi
+
+	#SSH
+
+	if [ "$1" == "ssh" ] && [ "$2" == "start" ]; then
+		$busybox chroot $mnt sudo service ssh start
+	fi
+	if [ "$1" == "ssh" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt sudo service ssh stop
+	fi
+
+	#UPDATE
+
+	if [ "$1" == "update" ]; then
+		LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt sudo /usr/bin/start-update.sh
+	fi
+
+	#Disable WLAN1
+
+	if [ "$1" == "wifi-disable" ]; then
+		LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt sudo /usr/bin/stop-wlan1.sh
+	fi
+
+	#WIFITE
+
+	if [ "$1" == "wifite" ]; then
+		$busybox chroot $mnt sudo /bin/bash -c "chmod 777 /dev/null"
+		ifconfig wlan1 up
+		sleep 3
+		LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt sudo /usr/bin/python /usr/bin/wifite
+	fi
+
+	#FRUITYWIFI
+
+	if [ "$1" == "fruitywifi" ] && [ "$2" == "start" ]; then
+		$busybox chroot $mnt /etc/init.d/php7-fpm start
+		$busybox chroot $mnt /etc/init.d/fruitywifi start
+		$busybox chroot $mnt /etc/init.d/nginx start
+		sleep 15
+        am start -a android.intent.action.VIEW -d http://127.0.0.1:8000
+	fi
+	if [ "$1" == "fruitywifi" ] && [ "$2" == "stop" ]; then
+		$busybox chroot $mnt /etc/init.d/fruitywifi stop
+		$busybox chroot $mnt /etc/init.d/php7-fpm stop
+		$busybox chroot $mnt /etc/init.d/nginx stop
+	fi
+
+	#MACCHANGER
+	# Usage:	bootkali macchanger <mac address> <interface>
+	#		bootkali macchanger random <interface>
+
+	if [ "$1" == "macchanger_random" ]; then
+		$busybox chroot $mnt sudo /usr/bin/macchanger --random $2
+	fi
+	if [ "$1" == "macchanger_custom" ]; then
+		$busybox chroot $mnt sudo /usr/bin/macchanger --mac=$2 $3
+	fi
+	if [ "$1" == "macchanger_original" ]; then
+		$busybox chroot $mnt sudo /usr/bin/macchanger --permanent $2
+	fi
+
+	#GPSD
+	# Usage:	bootkali start_gpsd <listen port>
+
+	if [ "$1" == "start_gpsd" ]; then
+		$busybox chroot $mnt sudo /usr/sbin/gpsd -n tcp://127.0.0.1:$2
+	fi
+
+
+	#KALIMENU
+
+	if [ "$1" == "kalimenu" ]; then
+		$busybox chroot $mnt sudo /usr/bin/kalimenu
+	fi
+
+	#YCABLE
+
+	if [ "$1" == "ycable" ] && [ "$2" == "start" ]; then
+		if [ -f "/sys/module/msm_otg/parameters/usbhost_charge_mode" ]; then
+			echo "1" > /sys/module/msm_otg/parameters/usbhost_charge_mode
+		fi
+		if [ -f "/sys/module/tegra_otg/parameters/tegra_otg_on_charging" ]; then
+			echo "Y" > /sys/module/tegra_otg/parameters/tegra_otg_on_charging
+		fi
+		if [ -f "/sys/module/dwc3/parameters/aca_enable" ]; then
+			echo "Y" > /sys/module/dwc3/parameters/aca_enable
+		fi
+		if [ -f "/sys/module/dwc3/parameters/otg_charging" ]; then
+			echo "Y" > /sys/module/dwc3/parameters/otg_charging
+		fi
+	fi
+
+	if [ "$1" == "ycable" ] && [ "$2" == "stop" ]; then
+		if [ -f "/sys/module/msm_otg/parameters/usbhost_charge_mode" ]; then
+			echo "0" > /sys/module/msm_otg/parameters/usbhost_charge_mode
+		fi
+		if [ -f "/sys/module/tegra_otg/parameters/tegra_otg_on_charging" ]; then
+			echo "N" > /sys/module/tegra_otg/parameters/tegra_otg_on_charging
+		fi
+		if [ -f "/sys/module/dwc3/parameters/aca_enable" ]; then
+			echo "N" > /sys/module/dwc3/parameters/aca_enable
+		fi
+		if [ -f "/sys/module/dwc3/parameters/otg_charging" ]; then
+			echo "N" > /sys/module/dwc3/parameters/otg_charging
+		fi
+	fi
+
+	#CUSTOM BUTTONS
+
+	if [ "$1" == "custom_cmd" ]; then
+		commmand=""
+		LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+		while test $# -gt 0
+		do
+			shift
+			commmand=${commmand}" "$1
+		done
+		$busybox chroot $mnt sudo $commmand
+	fi
+
+	#SearchSploit convert_exploitdb_to_csv
+
+	if [ "$1" == "convert_exploitdb" ]; then
+	    [ -f /sdcard/nh_files/SearchSploit ] && rm /sdcard/nh_files/SearchSploit
+		$busybox chroot $mnt sudo python /sdcard/nh_files/modules/csv2sqlite.py /usr/share/exploitdb/files_exploits.csv /sdcard/nh_files/SearchSploit $2
+		[ -f /sdcard/nh_files/SearchSploit ] && return 0 || return 1
+	fi
+
+	#MFOC MIFARE DUMP
+
+	if [ "$1" == "dumpmifare" ]; then
+		$busybox chroot $mnt /usr/bin/dumpmifare.sh
+	fi
+
+	#APT-GET
+	#Example: bootkali apt-get install "package-name package2"
+	#Packages don't have to be in quotes but it doesn't hurt
+	#Also, you can leave the packages blank and it'll just update/upgrade
+
+	if [ "$1" == "apt-get" ] && [ "$2" == "install" ]; then
+		echo -e "\e[32mHere we go!\n\nInstalling any new metapackages and update/upgrading.\n\nNote that you may be asked to interact during the installation of some packages.\n\n"
+		echo -e "kali-chroot$ /usr/bin/apt-get update\e[0m"
+		LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get update
+		if [ -z ${var+x} ] || [ "$3" != "" ]; then
+			echo -e "\e[32mkali-chroot$ /usr/bin/apt-get -y install "$3"\e[0m"
+			LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y install "$3"
+		fi
+		echo -e "\e[32mkali-chroot$ /usr/bin/apt-get -y dist-upgrade\e[0m"
+		LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y dist-upgrade
+		LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y install "$3"
+		echo -e "\e[32mkali-chroot$ /usr/bin/apt-get -y dist-upgrade\e[0m"
+		LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y dist-upgrade
+		echo -e "\e[32m"
+		printf "\n\nDone!\n\nPress the 'back' key to return to Nethunter.\n\nIf you noticed errors, press the up-arrow key (if your keyboard supports it) to review previously-issued commands.\n"
+		printf "And remember to use the 'Maintain Chroot' button in the Chroot Manager to keep your chroot up-to-date and to install new metapackages.\n\n"
+		echo -e "\e[0m"
+	fi
+	#Extract kali chroot with symlink.
+
+    if [ "$1" == "extract-chroot" ] && [ "$2" != "" ]; then
+    	$busybox chroot $mnt /bin/tar xzf "$2" --hard-dereference --keep-old-files --keep-directory-symlink -C "/" > /dev/null 2>&1
+    fi
+
+    #Backup kali chroot
+
+	if [ "$1" == "backup-chroot" ] && [ "$2" != "" ]; then
+		if [ -f "/sdcard/$2" ]; then
+			bklog "[-] /sdcard/$2 existed already, please rename the existed filename to another first."
+		else
+			$busybox chroot $mnt sudo /bin/tar czf "/sdcard/$2" --hard-dereference --exclude='./system' --exclude='./sys' --exclude='./proc' --exclude='./dev' --exclude='./sdcard' --exclude='./lib/modules' -C "/" .
+			bklog "[+] Done. Successfully backup to /sdcard/$2"
+		fi
+	fi
+
+	if [ "$1" == "test" ]; then
+        $busybox chroot $mnt sudo printenv
     fi
 fi
 
-# Run e2fsck everytime we umount the kali chroot image on enrypted device.
-if [ -f "$chroot_image" ]; then
-    bklog "[!] Running e2fsck to check image $chroot_image.."
-    e2fsck -y $chroot_image
+
+	#APT-GET
+	#Example: bootkali apt-get install "package-name package2"
+	#Packages don't have to be in quotes but it doesn't hurt
+	#Also, you can leave the packages blank and it'll just update/upgrade
+
+	if [ "$1" == "apt-get" ] && [ "$2" == "install" ]; then
+		echo -e "\e[32mHere we go!\n\nInstalling any new metapackages and update/upgrading.\n\nNote that you may be asked to interact during the installation of some packages.\n\n"
+		echo -e "kali-chroot$ /usr/bin/apt-get update\e[0m"
+		LANG=C PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get update
+		if [ -z ${var+x} ] || [ "$3" != "" ]; then
+			echo -e "\e[32mkali-chroot$ /usr/bin/apt-get -y install "$3"\e[0m"
+			LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y install "$3"
+		fi
+		echo -e "\e[32mkali-chroot$ /usr/bin/apt-get -y dist-upgrade\e[0m"
+		LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y dist-upgrade
+		LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y install "$3"
+		echo -e "\e[32mkali-chroot$ /usr/bin/apt-get -y dist-upgrade\e[0m"
+		LANG=C DEBIAN_FRONTEND=noninteractive PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin $busybox chroot $mnt /usr/bin/apt-get -y dist-upgrade
+		echo -e "\e[32m"
+		printf "\n\nDone!\n\nPress the 'back' key to return to Nethunter.\n\nIf you noticed errors, press the up-arrow key (if your keyboard supports it) to review previously-issued commands.\n"
+		printf "And remember to use the 'Maintain Chroot' button in the Chroot Manager to keep your chroot up-to-date and to install new metapackages.\n\n"
+		echo -e "\e[0m"
+	fi
 fi
-
-# Check again if chroot image is really umounted.
-if [ "$(losetup -a | grep $chroot_image)" ]; then
-    bklog "[!] $mnt is still being mounted. Something is wrong!" && read
-fi
-
-if [ -d "$mnt/system" ]; then
-    rmdir $mnt/system
-fi
-
-if [ -d "$mnt/sdcard" ]; then
-    rmdir $mnt/sdcard
-fi
-
-if [ -d "$mnt/external_sd" ]; then
-    rmdir $mnt/external_sd
-fi
-
-if [ $($busybox umount $mnt 2>&1 > /dev/null) ]; then
-    echo " [-] Unable to umount the kali chroot image."
-    echo " [-] Please close all the kali terminals and umount all the mointpoint on kali chroot first then try again."
-else
-    echo "unmounted kali-armhf"
-fi
-
-# Run e2fsck everytime it umount the kali chroot image.
-e2fsck -y /sdcard/kali-chroot.img
-
-export PATH=$PRESERVED_PATH
